services:
  web:
    image: account
    container_name: test
    entrypoint: ./bin -port=:8086 -timeout=5
    ports:
      - 8080:8080
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres:latest
    container_name: PostgresCont 
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db:
    driver: local
  
